name: Build New Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build --configuration Release
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release -o publish
    - name: Zip Release
      uses: montudor/action-zip@v1
      with:
        args: (cd publish && zip -qq -r -j ../MmsApi.zip *)
    - name: Make Version Number
      run: |
        echo "release=$(date +'%Y%m%d.%H%M%S') ARM" >> $GITHUB_ENV
        echo "version=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: MmsApi.zip
        generateReleaseNotes: true;
        name: ${{ env.release }}
        tag: ${{ env.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
